version: '3.9'
services:
##  Remember to change -> energy.env
#  MYSQL_HOST=<mysql> # name of the mysql service
#  MYSQL_USER=<your_new_user> # parameter specified inside .yml
#  MYSQL_PASSWORD=<your_new_psw>   # parameter specified inside .yml

  mysql: # <- same to specify inside .env as MYSQL_HOST
    image: mysql:latest
    container_name: mysql
    volumes:
    - ./Volumes/mysql:/var/lib/mysql
    environment:
    - MYSQL_USER=user  # same to specify inside .env AS MYSQL_USER
    - MYSQL_PASSWORD=psw # same to specify inside .env AS MYSQL_PASSWORD
    - MYSQL_ROOT_PASSWORD=psw
    - MYSQL_DATABASE=energy
    ports:
    - 3307:3306

  transfer_service:
    image: docker.pkg.github.com/gabrieleghisleni/energyproject/energy:latest
    container_name: transfer_service
    command: bash -c "sleep 60 && python Code/meteo_managers.py --create_tables --partially_populate"
    # we pass sleep 45 because the mysql must be ready so to be reachable from the script
    depends_on:
      - mysql
    env_file:
      - energy.env # make sure to change the #mysql_service inside .env as well!

  add_external_files_to_dbs:
    image: docker.pkg.github.com/gabrieleghisleni/energyproject/energy:latest
    container_name: add_external_files_to_dbs
    command: bash -c "python Code/meteo_managers.py
      --external_load_path  https://raw.githubusercontent.com/GabrieleGhisleni/EnergyProject/master/Documentation/Files_from_terna/load/load_07.csv?token=ARWCS6N5K7XNFWRWTNH3YHLA6ABWS
      --external_generation_path  https://raw.githubusercontent.com/GabrieleGhisleni/EnergyProject/master/Documentation/Files_from_terna/generation/1-jan-2020.csv?token=ARWCS6OAPBSDN3M27Q5WL3LA6ABUM,https://raw.githubusercontent.com/GabrieleGhisleni/EnergyProject/master/Documentation/Files_from_terna/generation/1-jan-2020.csv?token=ARWCS6OAPBSDN3M27Q5WL3LA6ABUM
      "
    depends_on:
      - mysql
    env_file:
      - energy.env

  add_internal_files_to_dbs:
    image: docker.pkg.github.com/gabrieleghisleni/energyproject/energy:latest
    container_name: add_internal_files_to_dbs
    command: bash -c "python Code/meteo_managers.py --internal_energy_files --internal_load_files"
    volumes:
      - ./Volumes/extra_files/energy:/src/Volumes/extra_files/energy
      - ./Volumes/extra_files/load:/src/Volumes/extra_files/load
    depends_on:
      - mysql
    env_file:
      - energy.env

  train_models:
    image: docker.pkg.github.com/gabrieleghisleni/energyproject/energy:latest
    container_name: train_models
    command: bash -c "python Code/models_manager.py --model_to_train all --aug"
    depends_on:
      - mysql
    env_file:
      - energy.env

