version: '3.9'
services:
##  Remember to change -> energy.env
#  MYSQL_HOST=<mysql> # name of the mysql service
#  MYSQL_USER=<your_new_user> # parameter specified inside .yml
#  MYSQL_PASSWORD=<your_new_psw>   # parameter specified inside .yml

  mysql: # <- same to specify inside .env as MYSQL_HOST
    image: mysql:latest
    container_name: mysql
    volumes:
    - ./Volumes/mysql:/var/lib/mysql
    environment:
    - MYSQL_USER=user  # same to specify inside .env AS MYSQL_USER
    - MYSQL_PASSWORD=psw # same to specify inside .env AS MYSQL_PASSWORD
    - MYSQL_ROOT_PASSWORD=psw
    - MYSQL_DATABASE=energy
    ports:
    - 3307:3306

  transfer_service:
    image: docker.pkg.github.com/gabrieleghisleni/energyproject/energy:latest
    container_name: transfer_service
    command: bash -c "sleep 45 && python Code/meteo_managers.py --create_tables --partially_populate"
    # we pass sleep 45 because the mysql must be ready so to be reachable from the script
    depends_on:
      - mysql
    env_file:
      - energy.env

  train_models:
    image: docker.pkg.github.com/gabrieleghisleni/energyproject/energy:latest
    container_name: train_models
    command: bash -c "python Code/models_manager.py --model_to_train all --aug"
    depends_on:
      - mysql
    env_file:
      - energy.env

